### ISSUE TITLE
Create logo/icon

### ISSUE THREAD

**Issue by brittanydionigi** [brittanystoroz/devtip-of-the-day#4]
Need a cute logo/icon. Anyone have any creative ideas??

**Comment by osamajandali** [comment]
I kinda like the idea of the existing one, so I have done a redesign of it.
How do you think about it?
![rabbit](https://user-images.githubusercontent.com/13832392/30482769-0436ba82-9a2d-11e7-8545-d193c41cc633.jpg)

**Comment by brittanydionigi** [comment]
This is so cute I love it!! Would you mind replacing the icon images I've put the `assets` directory and update the file paths to each icon in the `manifest.json` file?

**Comment by osamajandali** [comment]
I'm glad that you like it.
Yeah, sure I will update them and make PR.
